### ISSUE TITLE
Hands not showing, Start Framework: -1 Error

### ISSUE THREAD

**Issue by skymeson** [ViveSoftware/ViveSRWorksHand#2]
Using Unity 2017.4.15f1, importing SteamVR Plugin 1.2.3, and SRWorks Plugin 0.8.0.2 I'm getting several null pointer errors and Start Framework: -1 Error. 

Samples experiences work fine for me going through the same steps. Will try on Unity 2018 since there could be an issue with prefabs. 

Also, not sure if I am using the right version of SteamVR plugin. Had to role back to 1.2.3 because was getting other errors using version from asset store. 

Error 1
NullReferenceException: Object reference not set to an instance of an object
Vive.Plugin.SR.ViveSR_DualCameraImageCapture.GetDepthTexture (UnityEngine.Texture2D& imageDepth, System.Int32& frameIndex, System.Int32& timeIndex, UnityEngine.Matrix4x4& pose) (at Assets/ViveSR/Scripts/ViveSR_DualCameraImageCapture.cs:364)
Vive.Plugin.SR.ViveSR_DepthWarp.Start () (at Assets/ViveSR/Scripts/ViveSR_DepthWarp.cs:44)

Error 2
[ViveSR] Start Framework : -1
UnityEngine.Debug:LogError(Object)
Vive.Plugin.SR.<StartFrameworkCoroutine>c__Iterator0:MoveNext() (at Assets/ViveSR/Scripts/ViveSR.cs:108)

Error 3
NullReferenceException
Vive.Plugin.SR.ViveSR_DualCameraDepthCollider.SetColliderProcessEnable (Boolean value) (at Assets/ViveSR/Scripts/ViveSR_DualCameraDepthCollider.cs:194)
Vive.Plugin.SR.ViveSR_DualCameraDepthCollider.set_UpdateDepthCollider (Boolean value) (at Assets/ViveSR/Scripts/ViveSR_DualCameraDepthCollider.cs:56)
SRWorksHand.OpenDynamicHandCollider () (at Assets/ViveSRWorksHand/Scripts/SRWorksHand.cs:28)
SRWorksHand.SetDetectHand (UnityEngine.GameObject handObjNear, UnityEngine.GameObject handObjFar, UnityEngine.GameObject handObjArm) (at Assets/ViveSRWorksHand/Scripts/SRWorksHand.cs:364)
SRHandManager+<_waitReconstructMeshLoadDone>c__Iterator0.MoveNext () (at Assets/ViveSRWorksHand/Scripts/SRHandManager.cs:57)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)

**Comment by skymeson** [comment]
Requirements say 
ViveSRWorks Unity package: Vive-SRWorks-0.7.5.0-Unity-Plugin.unitypackage
But I can't find older plugin anywhere. Doesn't seem available anymore since they updated package. 

Can somebody get this working with the latest SRWorks plugin?
https://developer.vive.com/resources/knowledgebase/vive-srworks-sdk/

**Comment by dariol** [comment]
Hi I just updated the readme to reflect the new requirement on the main prefab in your scene with the latest SRWorks version (also check out the builds I posted for both versions under releases and updated unity package). If you are still having issues let me know.

**Comment by skymeson** [comment]
That worked for me. Just needed to enable settings in [ViveSR]. Closing issue. Thanks!
